// This file was auto-generated by Fern from our API Definition.

package ssoready

type GetSAMLRedirectURLRequest struct {
	// The SAML connection to start a SAML login for.
	//
	//	One of `samlConnectionId`, `organizationId`, or `organizationExternalId` must be specified.
	SAMLConnectionID *string `json:"samlConnectionId,omitempty" url:"-"`
	// The ID of the organization to start a SAML login for.
	//
	//	The primary SAML connection in this organization will be used for logins.
	//
	//	One of `samlConnectionId`, `organizationId`, or `organizationExternalId` must be specified.
	OrganizationID *string `json:"organizationId,omitempty" url:"-"`
	// The `externalId` of the organization to start a SAML login for.
	//
	//	The primary SAML connection in this organization will be used for logins.
	//
	//	One of `samlConnectionId`, `organizationId`, or `organizationExternalId` must be specified.
	OrganizationExternalID *string `json:"organizationExternalId,omitempty" url:"-"`
	// This string will be returned back to you when you redeem this login's SAML access code.
	//
	//	You can do anything you like with this `state`, but the most common use-case is to keep track of where to redirect
	//	your user back to after logging in with SAML.
	State *string `json:"state,omitempty" url:"-"`
}

type RedeemSAMLAccessCodeRequest struct {
	// The SAML access code to redeem.
	SAMLAccessCode *string `json:"samlAccessCode,omitempty" url:"-"`
}
