// This file was auto-generated by Fern from our API Definition.

package ssoready

type ScimListScimGroupsRequest struct {
	// The SCIM directory to list from.
	//
	// One of `scimDirectoryId`, `organizationId`, or `organizationExternalId` must be specified.
	ScimDirectoryID *string `json:"-" url:"scimDirectoryId,omitempty"`
	// The ID of the organization to list from. The primary SCIM directory of this organization is used.
	//
	// One of `scimDirectoryId`, `organizationId`, or `organizationExternalId` must be specified.
	OrganizationID *string `json:"-" url:"organizationId,omitempty"`
	// The `externalId` of the organization to list from. The primary SCIM directory of this organization is used.
	//
	// One of `scimDirectoryId`, `organizationId`, or `organizationExternalId` must be specified.
	OrganizationExternalID *string `json:"-" url:"organizationExternalId,omitempty"`
	// Pagination token. Leave empty to get the first page of results.
	PageToken *string `json:"-" url:"pageToken,omitempty"`
}

type ScimListScimUsersRequest struct {
	// The SCIM directory to list from.
	//
	// One of `scimDirectoryId`, `organizationId`, or `organizationExternalId` must be specified.
	ScimDirectoryID *string `json:"-" url:"scimDirectoryId,omitempty"`
	// The ID of the organization to list from. The primary SCIM directory of this organization is used.
	//
	// One of `scimDirectoryId`, `organizationId`, or `organizationExternalId` must be specified.
	OrganizationID *string `json:"-" url:"organizationId,omitempty"`
	// The `externalId` of the organization to list from. The primary SCIM directory of this organization is used.
	//
	// One of `scimDirectoryId`, `organizationId`, or `organizationExternalId` must be specified.
	OrganizationExternalID *string `json:"-" url:"organizationExternalId,omitempty"`
	// If specified, only users that are members of this SCIM group are returned.
	ScimGroupID *string `json:"-" url:"scimGroupId,omitempty"`
	// Pagination token. Leave empty to get the first page of results.
	PageToken *string `json:"-" url:"pageToken,omitempty"`
}
