// This file was auto-generated by Fern from our API Definition.

package management

type OrganizationsListOrganizationsRequest struct {
	// Pagination token. Leave empty to get the first page of results.
	PageToken *string `json:"-" url:"pageToken,omitempty"`
}
