// This file was auto-generated by Fern from our API Definition.

package management

type SCIMDirectoriesListSCIMDirectoriesRequest struct {
	// The organization the SCIM directories belong to.
	OrganizationID *string `json:"-" url:"organizationId,omitempty"`
	// Pagination token. Leave empty to get the first page of results.
	PageToken *string `json:"-" url:"pageToken,omitempty"`
}
