// This file was auto-generated by Fern from our API Definition.

package management

type CreateSetupURLRequest struct {
	// The organization that the setup URL is for.
	OrganizationID *string `json:"organizationId,omitempty" url:"-"`
	// Whether the setup URL lets the user manage SAML connections.
	CanManageSAML *bool `json:"canManageSaml,omitempty" url:"-"`
	// Whether the setup URL lets the user manage SCIM directories.
	CanManageSCIM *bool `json:"canManageScim,omitempty" url:"-"`
}
